--- Day 8: Playground ---

Equipped with a new understanding of teleporter maintenance, you confidently step onto the repaired teleporter pad.

You rematerialize on an unfamiliar teleporter pad and find yourself in a vast underground space which contains a giant playground!

Across the playground, a group of Elves are working on setting up an ambitious Christmas decoration project. Through careful rigging, they have suspended a large number of small electrical junction boxes.

Their plan is to connect the junction boxes with long strings of lights. Most of the junction boxes don't provide electricity; however, when two junction boxes are connected by a string of lights, electricity can pass between those two junction boxes.

The Elves are trying to figure out which junction boxes to connect so that electricity can reach every junction box. They even have a list of all of the junction boxes' positions in 3D space (your puzzle input).

For example:

162,817,812
57,618,57
906,360,560
592,479,940
352,342,300
466,668,158
542,29,236
431,825,988
739,650,466
52,470,668
216,146,977
819,987,18
117,168,530
805,96,715
346,949,466
970,615,88
941,993,340
862,61,35
984,92,344
425,690,689

This list describes the position of 20 junction boxes, one per line. Each position is given as X,Y,Z coordinates. So, the first junction box in the list is at X=162, Y=817, Z=812.

To save on string lights, the Elves would like to focus on connecting pairs of junction boxes that are as close together as possible according to straight-line distance. In this example, the two junction boxes which are closest together are 162,817,812 and 425,690,689.

By connecting these two junction boxes together, because electricity can flow between them, they become part of the same circuit. After connecting them, there is a single circuit which contains two junction boxes, and the remaining 18 junction boxes remain in their own individual circuits.

Now, the two junction boxes which are closest together but aren't already directly connected are 162,817,812 and 431,825,988. After connecting them, since 162,817,812 is already connected to another junction box, there is now a single circuit which contains three junction boxes and an additional 17 circuits which contain one junction box each.

The next two junction boxes to connect are 906,360,560 and 805,96,715. After connecting them, there is a circuit containing 3 junction boxes, a circuit containing 2 junction boxes, and 15 circuits which contain one junction box each.

The next two junction boxes are 431,825,988 and 425,690,689. Because these two junction boxes were already in the same circuit, nothing happens!

This process continues for a while, and the Elves are concerned that they don't have enough extension cables for all these circuits. They would like to know how big the circuits will be.

After making the ten shortest connections, there are 11 circuits: one circuit which contains 5 junction boxes, one circuit which contains 4 junction boxes, two circuits which contain 2 junction boxes each, and seven circuits which each contain a single junction box. Multiplying together the sizes of the three largest circuits (5, 4, and one of the circuits of size 2) produces 40.

Your list contains many junction boxes; connect together the 1000 pairs of junction boxes which are closest together. Afterward, what do you get if you multiply together the sizes of the three largest circuits?


In [60]:
from math import sqrt
from functools import reduce

In [2]:
test_path = "../test/test08_1.txt"
file_path = "day08.txt"

In [3]:
def get_locations(filepath: str = test_path) -> list:
    '''
    Gets the locations of the junction boxes from the file and returns them as a list of tuples
    '''

    with open(filepath, "r") as file:
        lines = file.readlines()
    
    locations = [line.strip() for line in lines]
    locations = [tuple(map(int, line.split(","))) for line in lines]
    return locations

In [4]:
get_locations()

[(162, 817, 812),
 (57, 618, 57),
 (906, 360, 560),
 (592, 479, 940),
 (352, 342, 300),
 (466, 668, 158),
 (542, 29, 236),
 (431, 825, 988),
 (739, 650, 466),
 (52, 470, 668),
 (216, 146, 977),
 (819, 987, 18),
 (117, 168, 530),
 (805, 96, 715),
 (346, 949, 466),
 (970, 615, 88),
 (941, 993, 340),
 (862, 61, 35),
 (984, 92, 344),
 (425, 690, 689)]

In [5]:
def calc_distance(coord1: tuple[int], coord2: tuple[int]) -> float:
    '''
    Calculates the distance between coordinate 1 and coordinate 2 and returns the distance as a float.
    '''
    return sqrt((coord1[0]-coord2[0])**2 + (coord1[1]-coord2[1])**2 + (coord1[2]-coord2[2])**2)

In [6]:
def test_calc_distance():
    assert calc_distance((1,0,0), (0,0,0)) == 1
    assert calc_distance((3,4,0), (0,0,0)) == 5
    assert calc_distance((1,1,0), (0,0,0)) - sqrt(2) <= 0.001

In [7]:
test_calc_distance()

In [20]:
def get_distances(locations: list) -> list:
    '''
    Creates a list of the distances between all locations and returns them as a list of tuples with (distance, start, destination)
    '''

    distances = []
    for i, starting_point in enumerate(locations[:-1]):
        for j, destination in enumerate(locations[i+1:], i):
            distance = calc_distance(starting_point, destination)
            distances.append((distance, starting_point, destination))
    distances.sort()
    return distances

In [21]:
locations = get_locations()
distances = get_distances(locations)
print(locations)
print(distances[:10])

[(162, 817, 812), (57, 618, 57), (906, 360, 560), (592, 479, 940), (352, 342, 300), (466, 668, 158), (542, 29, 236), (431, 825, 988), (739, 650, 466), (52, 470, 668), (216, 146, 977), (819, 987, 18), (117, 168, 530), (805, 96, 715), (346, 949, 466), (970, 615, 88), (941, 993, 340), (862, 61, 35), (984, 92, 344), (425, 690, 689)]
[(316.90219311326956, (162, 817, 812), (425, 690, 689)), (321.560258738545, (162, 817, 812), (431, 825, 988)), (322.36935338211043, (906, 360, 560), (805, 96, 715)), (328.11888089532425, (431, 825, 988), (425, 690, 689)), (333.6555109690233, (862, 61, 35), (984, 92, 344)), (338.33858780813046, (52, 470, 668), (117, 168, 530)), (344.3893145845266, (819, 987, 18), (941, 993, 340)), (347.59890678769403, (906, 360, 560), (739, 650, 466)), (350.786259708102, (346, 949, 466), (425, 690, 689)), (352.936254867646, (906, 360, 560), (984, 92, 344))]


In [22]:
def test_get_distances():

    locations = get_locations()
    distances = get_distances(locations)
    # check if the first three connections are tbween the right locations
    first, second, third = distances[:3]
    _, first_start, first_destination = first
    _, second_start, second_destination = second
    _, third_start, third_destination = third

    assert first_start, first_destination   == ((162, 817, 812), (425, 690, 689))
    assert second_start, second_destination == ((162, 817, 812), (431, 825, 988))
    assert third_start, third_destination   == ((906, 360, 560), (805, 96, 715))
    

In [23]:
test_get_distances()

In [86]:
def day08a(filepath: str = test_path, n=10) -> int:
    '''
    Connects the locoations together to form circuits and returns the product of the 
    '''
    n_copy = n
    locations  = get_locations(filepath)
    distances = get_distances(locations)

    circuits = []
    while distances and n > 0:

        # get the closest connection
        _, start, destination = distances.pop(0)
                
        start_match, destination_match = False, False
        for circuit in circuits:
            
            if start in circuit:
                start_match = circuit
            elif destination in circuit:
                destination_match = circuit
        
        # if start is in an existing match remove the circuit from circuits and add start to it
        if start_match:
            circuits.remove(start_match)
        # make start a set by itself
        else:
            start_match = set()
            start_match.add(start)
            
        # do the same for destination
        if destination_match:
            circuits.remove(destination_match)
        else:
            destination_match = set()
            destination_match.add(destination)

        # combine the two sets and append
        new_circuit = start_match.union(destination_match)
        circuits.append(new_circuit)
        n -= 1
        

    circuit_lengths = [len(circuit) for circuit in circuits]
    circuit_lengths.sort(reverse=True)

    product_length = reduce(lambda x, y: x*y, circuit_lengths[:3], 1)

    print("Day 08 part a:")
    print(f"After connecting {n_copy} junction boxes, the product of the size of the three largest circuits is {product_length}.")
    return product_length

In [87]:
day08a()

Day 08 part a:
After connecting 10 junction boxes, the product of the size of the three largest circuits is 40.


40

In [88]:
def test_day08a():
    assert day08a() == 40

In [89]:
test_day08a()

Day 08 part a:
After connecting 10 junction boxes, the product of the size of the three largest circuits is 40.


In [90]:
day08a(filepath=file_path, n=1000)

Day 08 part a:
After connecting 1000 junction boxes, the product of the size of the three largest circuits is 24360.


24360

--- Part Two ---

The Elves were right; they definitely don't have enough extension cables. You'll need to keep connecting junction boxes together until they're all in one large circuit.

Continuing the above example, the first connection which causes all of the junction boxes to form a single circuit is between the junction boxes at 216,146,977 and 117,168,530. The Elves need to know how far those junction boxes are from the wall so they can pick the right extension cable; multiplying the X coordinates of those two junction boxes (216 and 117) produces 25272.

Continue connecting the closest unconnected pairs of junction boxes together until they're all in the same circuit. What do you get if you multiply together the X coordinates of the last two junction boxes you need to connect?


In [126]:
def day08b(filepath: str = test_path) -> int:
    '''
    Connects the locoations together to form circuits and returns the product of the 
    '''

    locations  = get_locations(filepath)
    distances = get_distances(locations)
    circuits = []
    
    N = len(locations)
    last_connectors = 0, 0
    
    while distances:
        # get the closest connection
        _, start, destination = distances.pop(0)

        # check if we only have one last connection left
        if len(circuits) == 1 and len(circuits[0]) == N - 1:
            last_connectors = start[0], destination[0]
                
        start_match, destination_match = False, False
        for circuit in circuits:
            
            if start in circuit:
                start_match = circuit
            elif destination in circuit:
                destination_match = circuit
        
        # if start is in an existing match remove the circuit from circuits and add start to it
        if start_match:
            circuits.remove(start_match)
        # make start a set by itself
        else:
            start_match = set()
            start_match.add(start)
            
        # do the same for destination
        if destination_match:
            circuits.remove(destination_match)
        else:
            destination_match = set()
            destination_match.add(destination)
    
        # combine the two sets and append
        new_circuit = start_match.union(destination_match)
        circuits.append(new_circuit)
        
    result = last_connectors[0]*last_connectors[1]
    print("Day 08 part b:")
    print(f"The product of the X coordinates of the last two junction boxes to connect is {result}.")
    return result

In [127]:
def test_day08b():
    assert day08b() == 25272

In [128]:
test_day08b()

Day 08 part b:
The product of the X coordinates of the last two junction boxes to connect is 25272.


In [129]:
day08b(file_path)

Day 08 part b:
The product of the X coordinates of the last two junction boxes to connect is 2185817796.


2185817796